<?php

declare(strict_types=1);
/**
 * User: Houziaux mike : jenaye : mike@les-tilleuls.coop.
 */

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MembreRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends EntityRepository
{
    public function findByEmail($email)
    {
        $queryBuilder = $this->createQueryBuilder('m');

        return $queryBuilder
            ->where("m.email = '$email'")
            ->getQuery()->getResult();
    }
}
