<?php

declare(strict_types=1);
/**
 * User: Houziaux mike : jenaye : mike@les-tilleuls.coop
 */

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StatementRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatementRepository extends EntityRepository
{
}
