<?php
/**
 * Created by PhpStorm.
 * User: Houziaux mike : jenaye
 * Email : mike@les-tilleuls.coop
 * Date: 12/07/18
 * Time: 20:27
 */

namespace App\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * StatementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatementRepository extends EntityRepository
{

}